name: Create GitHub App Installation Token
author: jon wong <j@jnwng.com>
description: A GitHub Action to make it simpler to retrieve a GitHub App's installation access token, primarily to facilitate the composition of GitHub Actions workflows.
branding:
  color: green
  icon: link
inputs:
  appId:
    description: The GitHub App ID
    required: true
  installationId:
    description: The GitHub App installation ID
    required: true
  privateKey:
    description: The private key used to sign the JWT
    required: true
outputs:
  token:
    description: The generated RS256-signed JWT
runs:
  using: "node12"
  main: "dist/index.js"
